database:
  development:
    adapter: sqlite3
    database: database.db
  test:
    adapter: sqlite3
    database: database_test.db
  dafault:
    adapter: postgresql
    encoding: unicode
    pool: 5
